angular.module('privadas',
  [
    'angular-meteor',    
    'ngAnimate',
    'ngCookies',
    'ui.select',
    'ngSanitize',    
    'toastr',
    'ui.router',
    'ui.grid',
    'smartadmin',
    'datePicker',
    'ui.calendar',
    'ui.bootstrap'
  ]
);
